# Generated by Django 4.2.7 on 2025-06-03 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='사건번호')),
                ('title', models.CharField(max_length=200, verbose_name='사건명')),
                ('description', models.TextField(verbose_name='사건개요')),
                ('incident_date', models.DateTimeField(verbose_name='사건발생일시')),
                ('location', models.CharField(max_length=200, verbose_name='사건발생장소')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('status', models.CharField(choices=[('active', '수사중'), ('closed', '종료'), ('suspended', '보류')], default='active', max_length=20, verbose_name='수사상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '사건',
                'verbose_name_plural': '사건들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='미상', max_length=100, verbose_name='이름/별칭')),
                ('age_estimate', models.CharField(blank=True, max_length=20, verbose_name='추정 나이')),
                ('height_estimate', models.CharField(blank=True, max_length=20, verbose_name='추정 신장')),
                ('clothing_description', models.TextField(verbose_name='복장 특징')),
                ('reference_image_url', models.URLField(verbose_name='기준 사진 URL')),
                ('ai_person_id', models.CharField(max_length=50, verbose_name='AI 모델 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case', verbose_name='사건')),
            ],
            options={
                'verbose_name': '용의자',
                'verbose_name_plural': '용의자들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CCTVMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200, verbose_name='위치명')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('detected_at', models.DateTimeField(verbose_name='탐지시간')),
                ('confidence_score', models.FloatField(verbose_name='신뢰도')),
                ('crop_image_url', models.URLField(verbose_name='크롭 이미지 URL')),
                ('police_comment', models.TextField(blank=True, verbose_name='경찰 의견')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='확정 여부')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='경로 제외')),
                ('analysis_id', models.CharField(blank=True, max_length=100, verbose_name='분석 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cctv_markers', to='cases.case', verbose_name='사건')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cctv_markers', to='cases.suspect', verbose_name='용의자')),
            ],
            options={
                'verbose_name': 'CCTV 마커',
                'verbose_name_plural': 'CCTV 마커들',
                'ordering': ['detected_at'],
            },
        ),
    ]
