# Generated by Django 4.2.7 on 2025-06-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_cctvmarker_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cctvmarker',
            options={'ordering': ['detected_at', 'sequence_order'], 'verbose_name': 'CCTV 마커', 'verbose_name_plural': 'CCTV 마커들'},
        ),
        migrations.AddField(
            model_name='cctvmarker',
            name='sequence_order',
            field=models.PositiveIntegerField(default=0, verbose_name='경로 순서'),
        ),
    ]
